server:
  port: 8000
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8090
---
spring:
  profiles: prod
server:
  port: 80
  
---
propertyTest: test
propertyTestList: 1,2,3
property:
  test:
      value: property call test